version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - apt-get update -y
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - gradle build
      - echo docker pass
      - echo $docker_pass
      - docker build -t spring-security-items .
      - docker push drabzes/spring-security-items:latest
    finally:
      - echo Build finished

